f1 <- function(x) dnorm(x)
f2 <- function(x) dexp(x)
envelope <- c(f1, f2)
z <- c(-1, 0.5, 2)
# see code efficiency
#tmp <- tempfile()
#Rprof(tmp, interval = 0.1)
#a=draw_sample(envelope, z, num_of_samples = 5000)
#Rprof(NULL)
#summaryRprof(tmp)